defaults:
  - _self_
  - representations: default
  - splitting: default
  - backend: sklearn
  - grid_search: default

data_root: /home/alex/Pt_NMR/data  # adjust to local env
xyz_base: st_
xyz_dir:
  - ${data_root}/structures/train_split
  - ${data_root}/structures/test_split
central_atom: Pt
mode: write
ap_path: ${data_root}/atomic_props.json
task: train
report: full
zeta: 2
partitioned: true

experiment_name: example
